// <auto-generated />
using Alpha_WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alpha_WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220325142614_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12");

            modelBuilder.Entity("Alpha_WebAPI.Models.Chefe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Chefes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartamentoId = 1,
                            Nome = "Rodrigo"
                        },
                        new
                        {
                            Id = 2,
                            DepartamentoId = 2,
                            Nome = "Silvana"
                        });
                });

            modelBuilder.Entity("Alpha_WebAPI.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sigla")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Administrativo",
                            Sigla = "ADM"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Financeiro",
                            Sigla = "FIN"
                        });
                });

            modelBuilder.Entity("Alpha_WebAPI.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Documento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Documento = "113247897",
                            Nome = "Marta",
                            Sobrenome = "Silva"
                        },
                        new
                        {
                            Id = 2,
                            Documento = "124567415",
                            Nome = "Paula",
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 3,
                            Documento = "135218795",
                            Nome = "Laura",
                            Sobrenome = "Santos"
                        },
                        new
                        {
                            Id = 4,
                            Documento = "115155482",
                            Nome = "Luisa",
                            Sobrenome = "Kent"
                        },
                        new
                        {
                            Id = 5,
                            Documento = "135654357",
                            Nome = "Lucas",
                            Sobrenome = "Alves"
                        },
                        new
                        {
                            Id = 6,
                            Documento = "548468455",
                            Nome = "Pedro",
                            Sobrenome = "Rocha"
                        },
                        new
                        {
                            Id = 7,
                            Documento = "213546518",
                            Nome = "Paulo",
                            Sobrenome = "Silveira"
                        });
                });

            modelBuilder.Entity("Alpha_WebAPI.Models.FuncionarioChefe", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChefeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FuncionarioId", "ChefeId");

                    b.HasIndex("ChefeId");

                    b.ToTable("FuncionariosChefes");

                    b.HasData(
                        new
                        {
                            FuncionarioId = 1,
                            ChefeId = 1
                        },
                        new
                        {
                            FuncionarioId = 2,
                            ChefeId = 2
                        },
                        new
                        {
                            FuncionarioId = 3,
                            ChefeId = 2
                        },
                        new
                        {
                            FuncionarioId = 4,
                            ChefeId = 2
                        },
                        new
                        {
                            FuncionarioId = 5,
                            ChefeId = 2
                        },
                        new
                        {
                            FuncionarioId = 6,
                            ChefeId = 1
                        },
                        new
                        {
                            FuncionarioId = 7,
                            ChefeId = 1
                        });
                });

            modelBuilder.Entity("Alpha_WebAPI.Models.Chefe", b =>
                {
                    b.HasOne("Alpha_WebAPI.Models.Departamento", "Departamento")
                        .WithMany("Chefes")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Alpha_WebAPI.Models.FuncionarioChefe", b =>
                {
                    b.HasOne("Alpha_WebAPI.Models.Chefe", "Chefe")
                        .WithMany("FuncionariosChefes")
                        .HasForeignKey("ChefeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alpha_WebAPI.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
